server:
  port: 9000

spring.profiles.include: db

spring:
  jpa:
    show-sql: true
    generate-ddl: false  # 로컬 환경
    hibernate:
      ddl_auto: none # 로컬 환경
      dialect: 'org.hibernate.dialect.MySQL5Dialect'
  freemarker:
    template-loader-path: 'classpath:/templates'
    suffix: .ftl
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://yh-toy-database-2.cluster-cki3kdutd3oc.ap-northeast-2.rds.amazonaws.com:3306/yh_toy_database_2?characterEncoding=utf8"
    username: admin
#    password:
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: "spring:session"

jwt:
  token:
    header: Authorization
    issuer: woowabros
    secret: F948937D2B793758ADFFECBD19B719CF1C5367B1CD96E7B4A72B41D69E2FFE24

auth:
  redirect-url: 'http://localhost:8080/api/auth/callback'
  client-id: 'test123'
  client-secret: 'pw123'
  authCode: 'secretCode'

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type: TRACE