server:
  port: 8080

spring.profiles.include: db

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl_auto: none # 로컬 환경
        dialect: 'org.hibernate.dialect.MySQL5Dialect'
    generate-ddl: false  # 로컬 환경
  freemarker:
    template-loader-path: 'classpath:/templates'
    suffix: .ftl
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: 'yh-toy-redis-2.8vqaql.ng.0001.apn2.cache.amazonaws.com'
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: "spring:session"

jwt:
  token:
    header: Authorization
    issuer: woowabros

auth:
  redirect-url: 'http://yh-toy-service.tk/api/auth/callback'
  client-id: 'test123'
  client-secret: 'pw123'
  server-url: 'http://yh-toy-auth-lb-939789643.ap-northeast-2.elb.amazonaws.com'

resource:
  server-url: 'http://yh-toy-resource-lb-2070114823.ap-northeast-2.elb.amazonaws.com'

oauth:
  authserver: 'http://yh-toy-auth-lb-939789643.ap-northeast-2.elb.amazonaws.com/authorize'
  resourceserver: 'http://yh-toy-resource-lb-2070114823.ap-northeast-2.elb.amazonaws.com/join'


logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type: TRACE

